const FlightsData = [
  {
    iata: "BOM",
    icon: "https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png",
    label: "Mumbai",
    airportName: "Chhatrapati Shivaji International Airport",
    country: "India",
    countryCode: "IN",
    group_type: "",
  },
  {
    iata: "DEL",
    icon: "https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png",
    label: "New Delhi",
    airportName: "Indira Gandhi International Airport",
    country: "India",
    countryCode: "IN",
    group_type: "",
  },
  {
    iata: "BKK",
    icon: "https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png",
    label: "Bangkok",
    airportName: "Bangkok",
    country: "Thailand",
    countryCode: "TH",
    group_type: "",
  },
  {
    iata: "BLR",
    icon: "https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png",
    label: "Bengaluru",
    airportName: "Bengaluru International Airport",
    country: "India",
    countryCode: "IN",
    group_type: "",
  },
  {
    iata: "PNQ",
    icon: "https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png",
    label: "Pune",
    airportName: "Pune Airport",
    country: "India",
    countryCode: "IN",
    group_type: "",
  },
  {
    iata: "HYD",
    icon: "https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png",
    label: "Hyderabad",
    airportName: "Rajiv Gandhi International Airport",
    country: "India",
    countryCode: "IN",
    group_type: "",
  },
  {
    iata: "CCU",
    icon: "https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png",
    label: "Kolkata",
    airportName: "Netaji Subhash Chandra Bose International Airport",
    country: "India",
    countryCode: "IN",
    group_type: "",
  },
  {
    iata: "MAA",
    icon: "https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png",
    label: "Chennai",
    airportName: "Chennai International Airport",
    country: "India",
    countryCode: "IN",
    group_type: "",
  },
  {
    iata: "GOI",
    icon: "https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png",
    label: "Goa - Dabolim Airport",
    airportName: "Goa Dabolim International Airport",
    country: "India",
    countryCode: "IN",
    group_type: "",
  },
  {
    iata: "DXB",
    icon: "https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png",
    label: "Dubai",
    airportName: "Dubai International",
    country: "United Arab Emirates",
    countryCode: "AE",
    group_type: "",
  },
];
export default FlightsData;
